NIFTY_50 = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK",
    "HINDUNILVR", "SBIN", "BHARTIARTL", "ITC", "KOTAKBANK",
    "LT", "HCLTECH", "AXISBANK", "BAJFINANCE", "ASIANPAINT",
    "MARUTI", "SUNPHARMA", "TITAN", "ULTRACEMCO", "WIPRO",
    "ONGC", "NTPC", "POWERGRID", "COALINDIA", "BPCL",
    "TECHM", "NESTLEIND", "DRREDDY", "DIVISLAB", "CIPLA",
    "BAJAJFINSV", "HINDALCO", "JSWSTEEL", "TATASTEEL", "GRASIM",
    "ADANIENT", "ADANIPORTS", "APOLLOHOSP", "EICHERMOT", "HEROMOTOCO",
    "BRITANNIA", "INDUSINDBK", "SBILIFE", "HDFCLIFE", "TATACONSUM",
    "BAJAJ-AUTO", "UPL", "TATAMOTORS", "M&M", "LTIM",
]

HIGH_VOLUME_EXTRAS = [
    "BANKBARODA", "PNB", "CANBK", "UNIONBANK", "IDFCFIRSTB",
    "VEDL", "NMDC", "SAIL", "NATIONALUM", "JINDALSTEL",
    "IDEA", "ZEEL", "NETWORK18", "TV18BRDCST", "STARHEALTH",
    "IRCTC", "HAL", "BEL", "BHEL", "RVNL",
    "RECLTD", "PFC", "IRFC", "HUDCO", "NBCC",
]

INDEX_INSTRUMENTS = [
    "NIFTY 50",
    "NIFTY BANK",
    "NIFTY FIN SERVICE",
]

OPTIONS_UNIVERSE = [
    "NIFTY",
    "BANKNIFTY",
    "FINNIFTY",
]

SECTOR_MAP = {
    "HDFCBANK": "BANKING", "ICICIBANK": "BANKING", "KOTAKBANK": "BANKING",
    "AXISBANK": "BANKING", "SBIN": "BANKING", "INDUSINDBK": "BANKING",
    "BANKBARODA": "BANKING", "PNB": "BANKING", "CANBK": "BANKING",
    "IDFCFIRSTB": "BANKING",

    "RELIANCE": "OIL_GAS", "ONGC": "OIL_GAS", "BPCL": "OIL_GAS",

    "TCS": "IT", "INFY": "IT", "HCLTECH": "IT", "WIPRO": "IT",
    "TECHM": "IT", "LTIM": "IT",

    "BAJFINANCE": "NBFC", "BAJAJFINSV": "NBFC", "SBILIFE": "INSURANCE",
    "HDFCLIFE": "INSURANCE",

    "SUNPHARMA": "PHARMA", "DRREDDY": "PHARMA", "CIPLA": "PHARMA",
    "DIVISLAB": "PHARMA", "APOLLOHOSP": "HEALTHCARE",

    "MARUTI": "AUTO", "TATAMOTORS": "AUTO", "M&M": "AUTO",
    "HEROMOTOCO": "AUTO", "BAJAJ-AUTO": "AUTO", "EICHERMOT": "AUTO",

    "JSWSTEEL": "METALS", "TATASTEEL": "METALS", "HINDALCO": "METALS",
    "VEDL": "METALS", "SAIL": "METALS", "NMDC": "METALS",

    "LT": "INFRA", "NTPC": "POWER", "POWERGRID": "POWER",
    "COALINDIA": "ENERGY", "ADANIPORTS": "PORTS",

    "HINDUNILVR": "FMCG", "ITC": "FMCG", "BRITANNIA": "FMCG",
    "NESTLEIND": "FMCG", "TATACONSUM": "FMCG",

    "ASIANPAINT": "PAINTS", "TITAN": "CONSUMER",
    "ULTRACEMCO": "CEMENT", "GRASIM": "CEMENT",
    "BHARTIARTL": "TELECOM", "IDEA": "TELECOM",
    "ADANIENT": "CONGLOMERATE", "IRCTC": "TRAVEL",
    "HAL": "DEFENCE", "BEL": "DEFENCE", "BHEL": "CAPITAL_GOODS",
}

FULL_UNIVERSE = NIFTY_50 + HIGH_VOLUME_EXTRAS


def get_sector(symbol: str) -> str:
    return SECTOR_MAP.get(symbol, "OTHER")
